force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHours__c.field-meta.xml
<CustomField>
    <fullName>QuantityHours__c</fullName>
    <label>QuantityHours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/StartProjectManuallyTest.cls
@isTest
public class StartProjectManuallyTest {
    static testMethod void validateTrigger() {
		Project__c sinSquad = new Project__c(Name='Project Test 1', StartDate__c=Date.today(), Status__c='Pre Kickoff',
                                             Amount__c=5000, ProjectManager__c= '005Dp000001WLkRIAW', QuantityHours__c= 10);
        
        Project__c proyecto2 = new Project__c(Name='Project Test 2', StartDate__c=Date.today(), Status__c='Pre Kickoff',
                                             Amount__c=1, ProjectManager__c= '005Dp000001WLkRIAW', 	SquadLead__c= '005Dp000001WLkRIAW',  QuantityHours__c= 10);
        
        Project_Resources__c pr1 = new Project_Resources__c (Project__c= sinSquad.Id, 	Rate_Per_Hours_Num__c= 10,	RequieredHours__c = 20);
        Project_Resources__c pr2 = new Project_Resources__c (Project__c= proyecto2.Id, 	Rate_Per_Hours_Num__c= 10,	RequieredHours__c = 20);
        
        
        
        
        
   }
}