force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>Project Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/fields/HoursPending__c.field-meta.xml
<CustomField>
    <fullName>HoursPending__c</fullName>
    <formula>5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HoursPending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/HoursPerRole__c.field-meta.xml
<CustomField>
    <fullName>HoursPerRole__c</fullName>
    <label>HoursPerRole</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Resources__c/fields/HoursAllocated__c.field-meta.xml
<CustomField>
    <fullName>HoursAllocated__c</fullName>
    
   
    <label>HoursAllocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resources__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/resourcesAllocation.cls
public with sharing class resourcesAllocation {

 
  //List of the roles with pending time to be assigned
  @AuraEnabled(cacheable=true)
  public static List <Project_Line_Item__c> getRolesWhithoutAssignment (Id projectId) {
   List<Project_Line_Item__c> rolesWithoutAssignment =
                   [
                   SELECT Id, Role__c, HoursPending__c, HoursPerRole__c, HoursAllocated__c 
                   FROM Project_Line_Item__c 
                   WHERE Project__c = : projectId
                   AND HoursPending__c > 0     
                   ];
         
   return rolesWithoutAssignment; 
 }

 //List of available employees by role
 @AuraEnabled(cacheable=true)
 public static List <User> getAvailableEmployeesByRole (String roleName, String projectId){

   //Find the project
   Project__c project =
                   [
                   SELECT Id, Name, StartDate__c, EndDate__c, Amount__c
                   FROM Project__c
                   WHERE Id = : projectId
                   ];

   //Find available users for the project
   List <User> resources = 
                   [
                   SELECT Id , FirstName, LastName, UserRole.Name, Rate__c,
                   (
                       SELECT StartDate__c, EndDate__c, Project__c 
                       FROM Project_Resources__r
                       WHERE (StartDate__c >=: project.StartDate__c AND StartDate__c <=: project.EndDate__c)
                       OR (EndDate__c >=: project.StartDate__c AND EndDate__c <=: project.EndDate__c)
                   )
                   FROM User
                   WHERE UserRole.Name = : roleName
                   
                   ];
   
   //List for available resources
   List<User> availableResources = New List<User>();

   for (User user : resources){
       if(user.Project_Resources__r.isEmpty()){
           availableResources.add(user);
       }
   }
       
   return availableResources;    
 }

 @AuraEnabled(cacheable=true)
 public static List <Project_Line_Item__c> getHoursPendingByRole (Id projectId, String roleName) {
   List <Project_Line_Item__c> hoursPending = 
                   [
                   SELECT HoursPending__c
                   FROM Project_Line_Item__c
                   WHERE Project__c = : projectId
                   AND HoursPending__c > 0
                   AND Role__c = : roleName
                   ];
               
   return hoursPending; 
 }

 @AuraEnabled
 public static Boolean allocateResources(String allocationJSON){

   List<Project_Resources__c> projectResources = (List<Project_Resources__c>) JSON.deserialize(allocationJSON, List<Project_Resources__c>.class);
   
   insert projectResources;

   return true;
 }

}