force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>Project Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/fields/HoursPerRole__c.field-meta.xml
<CustomField>
    <fullName>HoursPerRole__c</fullName>
    <label>HoursPerRole</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resources__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Resources__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/allocateResources.cls
public with sharing class allocateResources {
    @AuraEnabled(cacheable=true)
    public static Map<string, List<user>> availableResourcesPerRole(Id recordId) {
    
    //Project dates
    Project__c dates = [
                        SELECT StartDate__c,
                        EndDate__c
                        FROM Project__c
                        WHERE Project__c.Id =: recordId
                        ];

    //Look for not available resources
    List<Project_Resources__c> notAvailableResources = 
                        [
                        SELECT User__c
                        FROM Project_Resources__c
                        WHERE (StartDate__c = NULL OR EndDate__c = NULL)
                        OR (StartDate__c <= : dates.EndDate__c)
                        OR (EndDate__c <= : dates.StartDate__c)
                        ];

    //Set Id of available project resources
    Set<Id> notAvailableResourceId = New Set<Id>();
    for (Project_Resources__c nar : notAvailableResources){
        notAvailableResourceId.add(nar.User__c);
    }

    //Determines which roles the project has sold
    List<Project_Line_Item__c> projectRoles =
                        [
                        SELECT Role__c, HoursPerRole__c
                        FROM Project_Line_Item__c
                        WHERE Project__r.Id =: recordId
                        ORDER BY Role__c ASC
                        ];

    //Set string of project roles
    Set<String> pRoles = New Set<String>();
    for(Project_Line_Item__c pr : projectRoles){
        pRoles.add(pr.Role__c);
    }

    //List of available employees
    List<User> availableEmployee =
                        [
                        SELECT FirstName, LastName, UserRole.Name, Rate__c
                        FROM User
                        WHERE User.Id NOT IN : notAvailableResourceId
                        AND UserRole.Name IN : pRoles
                        ORDER BY UserRole.Name ASC
                        ];

    //Map of available resources by role
    Map<String, List<User>> availableEmployeesPerRole = New Map<String, List<User>>();

        //Create a key per role in the project
        for (Project_Line_Item__c pr : projectRoles){
            if(!availableEmployeesPerRole.containsKey(pr.Role__c)){
                availableEmployeesPerRole.put(pr.Role__c, New List<User>());
            }
        }

        //Add employees on the Map according to the role
        for (User employee : availableEmployee){
            availableEmployeesPerRole.get(employee.UserRole.Name).add(employee);
        }

        return availableEmployeesPerRole;     


    }

}